import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import './globals.css';
import { GlobalContextProvider } from '@/contexts';

const kanit = Kanit({ weight: ['100', '200', '300', '400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className="dark scroll-smooth overflow-x-hidden"
      lang="en"
      suppressHydrationWarning
    >
      <GlobalContextProvider>
        <body className={`${kanit.className}`}>{children}</body>
      </GlobalContextProvider>
    </html>
  );
}
